name: Multiline config
description: This module allows you export configuration strings as multiline.
package: Configuration

# core: 8.x
type: module

# Information added by Drupal.org packaging script on 2019-03-22
version: '8.x-1.0'
core: '8.x'
project: 'multiline_config'
datestamp: 1553258908
