name: template
recipe: drupal8
config:
  php: '7.2'
  via: apache
  webroot: docroot
  database: mariadb
  drush: "*"

tooling:
  'db-import install/database/install.sql':
    service: :host
    description: Imports a dump file into a database service
    cmd: /helpers/sql-import.sh
    options:
      host:
        description: The database service to use
        default: database
        alias:
          - h
      no-wipe:
        description: Do not destroy the existing database before an import
        boolean: false

proxy:
  index:
    - solr.template.lndo.site:8983
  pma:
    - pma.template.lndo.site

services:
  appserver:
    config:
      conf: lando/php/php.ini
  index:
    type: solr
    portforward: 9999
    core: template
    config:
      conf: lando/solr
  pma:
    type: phpmyadmin
    hosts:
      - database

events:
  post-start:
    - appserver: /bin/bash $LANDO_MOUNT/lando/scripts/drupal-settings.sh
    - appserver: /bin/bash $LANDO_MOUNT/lando/scripts/drush-aliases.sh
