name: template
recipe: drupal8
config:
  php: '7.2'
  via: apache
  webroot: docroot
  database: mariadb
  drush: "*"

proxy:
  index:
    - solr.template.lndo.site:8983
  pma:
    - pma.template.lndo.site

services:
  appserver:
    config:
      conf: lando/php/php.ini
  database:
    creds: {
      user: "template",
      password: "template",
      database: "template"
    }
  index:
    type: solr
    portforward: 9999
    core: template
    config:
      conf: lando/solr
  pma:
    type: phpmyadmin
    hosts:
      - database

events:
  post-start:
    - appserver: /bin/bash $LANDO_MOUNT/lando/scripts/drupal-settings.sh
    - appserver: /bin/bash $LANDO_MOUNT/lando/scripts/drush-aliases.sh
